### ISSUE TITLE
Lottery Items

### ISSUE THREAD

**Issue by GabrieleGrimme** [GabrieleGrimme/capstone-project#2]
### Value Statement
As a user I want to know what i can win that day.

### Description
Give a short description of the give aways today.

### Acceptance Criteria
- [ ]  show the user what he/she can win today
- [ ]  show only the gift of the day

### Complexity
m

### Tasks
- [ ] create an API with the gifts, id, date to show there can be more than one gift per day
- [ ] placed at the right date
- [ ] make a fetch from API
