### ISSUE TITLE
Quiz 

### ISSUE THREAD

**Issue by GabrieleGrimme** [GabrieleGrimme/capstone-project#3]
### Value Statement
As a user I want to be challenged by a quiz to win as a reward the advents gift. I want to be entertained: the questions should neither be too easy nor too difficult and I want a chance to take part in the advents gift lottery, so I want to have another question if it is too difficult to resolve -- I do not want to feel stupid. 

### Description
The quiz is about music and the artists. The user has to choose between 4 possible answers the right one. Only if he/she clicks the right one, he/she can send an email. 

### Acceptance Criteria
- [ ]  the user clicks the wrong answer --> give him/her the hint "Wrong answer"
- [ ]  if the user does not know the right answer, he/she can have another question
- [ ] the user clicks the right answer, he/she can send an email to take part in the lottery of the above signed gifts of the day

### Complexity
M/L

### Tasks
- [ ] create an API with at least 30 to 50 questions and its answers, mark the right and the wrong ones
- [ ] the API: Q, right answer, three wrong answers
- [ ] create a field where the question is shown (a little bit of glam)
- [ ] make a fetch
- [ ] make a useState
- [ ] create the fields for the 4 answers with radio buttons
- [ ] do not forget to code which is the right one
- [ ]  add 2 buttons "clear" and "new question"
- [ ] make functions to make clear and new question button work
