### ISSUE TITLE
Radioplayer

### ISSUE THREAD

**Issue by GabrieleGrimme** [GabrieleGrimme/capstone-project#4]
### Value Statement
As a user I want to know with whom I am dealing with but I don't want to be spammed with superfluous information. Some music would do fine.

### Description
Link to radio player and website.

### Acceptance Criteria
- [ ]  The user can listen to music while solving the quiz
- [ ]  He/she can have infos how to find the radio player online and can visit the website

### Complexity
s

### Tasks
- [ ] insert the radio player
- [ ] maybe show the title which is played at that moment
- [ ] add the link to the website
