### ISSUE TITLE
Email Field

### ISSUE THREAD

**Issue by GabrieleGrimme** [GabrieleGrimme/capstone-project#5]
### Value Statement
As a user I want to get easily in contact and sent emails.

### Description
The Email opens when right answer in the quiz is clicked.

### Acceptance Criteria
- [ ] the user gets the email field  
- [ ]  he/she types in his/her email
- [ ] he/she can abort the process or sent the email

### Complexity
m

### Tasks
- [ ] create a database to put in the users email address to check if user is attending the quiz more than once a day
- [ ] also put in his/her answer an day of taking part
- [ ] connect the database to the app
- [ ] write the right answer and day of attendance to the database
- [ ] When email is sent, give Info when user is getting informed if he/she has won.
